name: zapstore_cli
description: The permissionless app store powered by your social network
version: 0.1.0 # (!) Also update kVersion (!)
repository: https://github.com/zapstore/zapstore-cli

environment:
  sdk: ^3.3.4

dependencies:
  args: ^2.5.0
  cli_spin: ^1.0.1
  collection: ^1.18.0
  dotenv: ^4.2.0
  html2md: ^1.3.2
  http: ^1.2.2
  interact_cli: ^2.3.0
  path: ^1.9.0
  process_run: ^1.0.0+1
  purplebase: ^0.1.1
  riverpod: ^2.5.1
  tint: ^2.0.1
  universal_html: ^2.2.4
  yaml: ^3.1.2

dependency_overrides:
  purplebase:
    # path: ../purplebase
    git:
      url: https://github.com/purplebase/purplebase
      ref: a4e808f21c68eeedc6d48a17ac61cda893ecd382

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
