name: zapstore_cli
description: The permissionless app store powered by your social network
version: 0.0.2
repository: https://github.com/zapstore/zapstore-cli

environment:
  sdk: ^3.3.4

dependencies:
  args: ^2.5.0
  cli_dialog: ^0.5.0
  cli_spin: ^1.0.1
  cli_util: ^0.4.1
  collection: ^1.18.0
  http: ^1.2.2
  path: ^1.9.0
  process_run: ^1.0.0+1
  purplebase: ^0.1.1
  riverpod: ^2.5.1

dependency_overrides:
  purplebase:
    git:
      url: https://github.com/purplebase/purplebase
      ref: 0.1.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
