name: zapstore_cli
description: The permissionless social package manager
version: 0.2.0 # (!) Also update kVersion (!)
repository: https://github.com/zapstore/zapstore-cli

environment:
  sdk: ^3.3.4

dependencies:
  archive: ^4.0.7
  args: ^2.5.0
  cli_spin: ^1.0.1
  collection: ^1.18.0
  dotenv: ^4.2.0
  html2md: ^1.3.2
  http: ^1.2.2
  interact_cli: ^2.3.0
  meta: ^1.16.0
  mime: ^2.0.0
  path: ^1.9.0
  process_run: ^1.0.0+1
  purplebase: ^0.1.1
  riverpod: ^2.5.1
  tint: ^2.0.1
  universal_html: ^2.2.4
  yaml: ^3.1.3

dependency_overrides:
  purplebase:
    # path: ../purplebase
    git:
      url: https://github.com/purplebase/purplebase
      ref: cbe8342031adf908c8243125e176f52739d400d8

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
